### ISSUE TITLE
List to add

### ISSUE THREAD

**Issue by icochecker** [cryptovibe/cryptovibe#5]
### To keep:
- ICO Check https://t.me/checkico
- FundRequest https://t.me/fundrequestofficial
- Jibrel Network https://t.me/jibrel_network
- Bluzelle https://t.me/bluzelle 
- NuCypher https://t.me/nucypher
- SalPay https://t.me/salpayico
- Akropolis https://t.me/akropolis_official

### New:
- [x] Seele https://t.me/seeletech
- [x] Unibright https://t.me/unibright_io
- [x] Constellation https://t.me/constellationcommunity
- [x] Boxmining https://t.me/Boxdatamining
- [x] Eximchain https://t.me/eximchain
- [x] Ontology network https://t.me/OntologyNetwork
- [x] XDAG https://t.me/dagger_cryptocurrency
- [x] Zilliqa https://t.me/zilliqachat
- [x] Matrix https://t.me/matrixainetwork
- [x] Omega One https://t.me/OmegaOnePlatform
- [x] POA Network https://t.me/oraclesnetwork
- [x] Dragon Chain https://t.me/dragontalk
- [x] Nuls https://t.me/Nulsio
- [x] Credits https://t.me/creditscom
- [x] Cosmos https://t.me/cosmosproject
- [x] Deep brain chain https://t.me/deepbrainchain
- [x] Substratum https://t.me/SubstratumCommunity
- [x] Cardstack https://telegram.me/cardstack
- [x] Wanchain https://t.me/WanchainCHAT
- [x] Dfinity https://t.me/dfinity
- [x] Neo https://t.me/Neo_Blockchain
- [x] Enigma https://t.me/enigmacatalyst
- [x] Sentinel Chain https://t.me/sentinelchain
- [x] Effect AI https://t.me/effectai
- [x] Kairos https://t.me/KairosICO
- [x] Origin https://t.me/originprotocol
- [x] PolicyPal Network https://t.me/PolicyPalNetwork
- [x] Hashgraph https://t.me/hashgraph
- [x] Viola.AI https://t.me/ViolaAI
- [x] Polymath https://t.me/polymathnetwork

**Comment by hterrence** [comment]
Done
